### ISSUE TITLE
Add `rocker run` command

### ISSUE THREAD

**Issue by alexander-yakushev** [grammarly/rocker#132]
When I use Rocker for running tests I want the last `RUN` to be executed unconditionally (even if all upper layers are cached). I can turn the last `RUN` into `CMD`, but then I have to separately execute `rocker build` and then `docker run`.

It would be convenient if I could build an image and then immediately run the `CMD` command. As an alternative, a way to forcefully invalidate a certain line in Rockerfile (as opposed to invalidate cache for the whole file with `--no-cache`) would solve my problem too.

**Comment by segfly** [comment]
@alexander-yakushev Will the `ATTACH` directive work for you? That's what I would use:
```dockerfile
FROM baseimage
RUN apt-get install ...
COPY /tests /tests
ATTACH /tests/runtests.sh
TAG myimage
```

I like this because the tests will only run if you use the `--attach` flag with `rocker build`. I think, the `ATTACH` directive may even stop the build (e.g. not tag a broken image) if the command returns nonzero like with `RUN`. You can also run tests at different stages with this with multiple `ATTACH` directives.

**Comment by ctrlok** [comment]
@alexander-yakushev for my personal usage I [made](https://github.com/ctrlok/rocker/tree/f-drop-cache-step) `DROP_CACHE` step. 
I like it, because it look much simpler than `ATTACH`. 
I don't understand how it can works in rocker ideology, so we need answer from maintainers.

**Comment by ctrlok** [comment]
ALSO, you can do something like that:
```
RUN touch 1
{{ if  .drop_cache }}
DROP_CACHE
{{ end }}
RUN touch 2
...
rocker build -var drop_cache=true
```
Or if's like that, but with attach flag.

**Comment by ybogdanov** [comment]
Thanks for requesting. Unfortunately, we are discontinuing this project. See the notice here: https://github.com/grammarly/rocker/blob/master/README.md

Closing this issue as we are not able to implement it. Sorry.
