### ISSUE TITLE
The sublime text file doesn't hightlight INCLUDE

### ISSUE THREAD

**Issue by bobef** [grammarly/rocker#29]
As it says in the title.

**Comment by ybogdanov** [comment]
@bobef do you use `INCLUDE`? Can you provide an example of where it is useful?

**Comment by rgpublic** [comment]
Hm. Sorry for the spam, but INCLUDE doesn't seem to work. I've just switched to rocker only because of the INCLUDE feature. I don't need any of the other features (at least not yet). INCLUDE is highlighted in Sublime but that's it:

FATA[0000] Unknown command: include  

I used e.g. this line:

INCLUDE "includes/init.rocker"

Unfortunately information on this command is really scarce....
