### ISSUE TITLE
COPY/ADD after MOUNT is not working

### ISSUE THREAD

**Issue by bobef** [grammarly/rocker#30]
I have to do `RUN cp -r` instead. Maybe I don't fully understand how rocker works, but I thought COPY should work.

With `RUN cp` the output looks like this:

```
[Rocker] MOUNT /apps/supplier/bonotel/master:/mounts/app
[Rocker]  ---> Using cache
[Rocker]  ---> 4230a21270a7
[Rocker] RUN cp -r /mounts/app /app
[Rocker]  ---> Running in 0c9f5fc7fead (image id = 4230a21270a7)
[Rocker] Removing intermediate container 0c9f5fc7fead
[Rocker]  ---> 355d08380396
```

from this:
```
MOUNT {{.project_local}}:/mounts/app
RUN cp -r /mounts/app /app
```
and with `COPY` it looks like this:

```
[Rocker] MOUNT /apps/supplier/bonotel/master:/mounts/app
[Rocker]  ---> Running in 0bb52f82a782 (image id = e29cae8d3df6)
[Rocker] Removing intermediate container 0bb52f82a782
[Rocker]  ---> 4230a21270a7
Step 0 : FROM 4230a21270a7684aa7a4ebb73f1ec15b99cff8ab2ccaa7663bae99faec61707a
 ---> 4230a21270a7
Step 1 : COPY /mounts/app /app
2015/09/27 13:34:28 Failed to process json stream error: mounts/app: no such file or directory
```

from this:
```
MOUNT {{.project_local}}:/mounts/app
COPY /mounts/app /app
```

In both cases I have many lines of Rockerfile after the copy before the end. I don't understand why rocker has to unmount before the file is finished building?

**Comment by ybogdanov** [comment]
Hi @bobef 

It's because `MOUNT` is a bit different thing. When you use it this way `MOUNT src:dest` it works like `docker run -v src:dest COMMAND` for all subsequent `RUN`s. Rocker falls back to `docker build` when it comes to other commands, such as `COPY`. To do that, it generates an intermediate `Dockerfile` and substitutes `FROM` with the current layer ID.

As an example, the following Rockerfile:

```Dockerfile
FROM ubuntu:latest
MOUNT .:/mounts/app
RUN cp -r /mounts/app /app
```

Will execute the following container:

```bash
docker run -v .:/mounts/app ubuntu:latest cp -r /mounts/app /app
```

In your case, `COPY` does not see the mounted directory under `/mounts/app` simply because rocker falls back to original `docker build`, which doesn't know anything about our stuff.

To achieve what you want, you can copy the source directory instead, because that's what you want, I guess:

```Dockerfile
COPY . /app
```
