### ISSUE TITLE
WARN[0000] Tar: Can't archive a file with includes

### ISSUE THREAD

**Issue by sebest** [grammarly/rocker#40]
If i try to use rocker in a folder that is a symlink to another folder i get the following error

$ rocker build
[Rocker] Building...
WARN[0000] Tar: Can't archive a file with includes
2015/10/06 16:43:29 Failed to build image: API error (500): Cannot locate specified Dockerfile: .rockertmp_Rockerfile_init

step to reproduce:
  504  mkdir folder
  505  ln -s folder link
  506  echo FROM scratch > link/Rockerfile
  507  cd link
  508  rocker build
  509  history

**Comment by ybogdanov** [comment]
Hi @sebest, thanks for reporting and sorry for the delay.

It looks like a bug in https://github.com/fsouza/go-dockerclient which us used as a client library to make a docker build through the API. Rocker v0.x falls back to the original `docker build` for things it can't do, or for Dockerfiles that do not have anything custom and though can be built with plain docker.
I don't think I'm going to fix this, since there is [Rocker v1](https://github.com/grammarly/rocker/tree/v1#note-on-v1-branch) that will be merged to master soon (it does not have this problem). You can try the new Rocker now, we are using at Grammarly for a few weeks already.

**Comment by ybogdanov** [comment]
Resolved in v1.0.0 release!
